docs: Bot製作ガイドライン2023の追加
approvers/docs pull request #5
Opened 2023-02-12 16:39 UTC by m2en

2020年・2021年の当時の記憶を辿りながらなので、間違っていたら指摘していってください。

2023-02-12 16:58 UTC, MikuroXina requested changes

2023-02-12 16:58 UTC, MikuroXina commented on pages/guideline/bot-create-guideline.mdx
> +Discord にはサーバー(ギルド)を制御するために権限システムというものが存在します。その中でも特にヤバい権限で **Administer**(管理者権限) というものがあります。
```suggestion
Discord にはサーバー(ギルド)を制御するために権限システムというものが存在します。その中でも特にヤバい権限で **Administrator**(管理者権限) というものがあります。
```
おそらく typo かと

2023-02-12 16:58 UTC, MikuroXina commented on pages/guideline/bot-create-guideline.mdx
> +3. `Privileged Gateway Intents` にある Intent を全てチェックマークボタンから有効化する
混乱を防ぐためにとりあえず全部の Intent を有効化するというのも擁護はできます. Bot の接続サーバーが増えれば制限が掛かりますからね.
しかし, 用途によっては有効にしなくてもいい Intent もあるのでちょっと説明不足に思います

2023-02-12 16:58 UTC, MikuroXina commented on pages/guideline/bot-create-guideline.mdx
> +![管理者権限](../../public/permission.png)
```suggestion
![Discordのロール編集画面における権限の設定で、管理者権限の項目に警告が表示されている](../../public/permission.png)
```
alt のテキストは画像の内容を代替するものにしましょう

2023-02-12 16:58 UTC, MikuroXina commented on pages/guideline/bot-create-guideline.mdx
> +```ts copy
この `copy` という指定は何でしょうか

2023-02-12 16:58 UTC, MikuroXina commented on pages/guideline/bot-create-guideline.mdx
> +### TypeScript / JavaScript
```suggestion
### Node.js
```
`process.env` などを使っている文脈からしてこちらが適切かと

2023-02-12 16:58 UTC, MikuroXina commented on pages/index.mdx
> +- [LaTex](https://nextra.site/docs/guide/latex)
ここに Nextra のガイドを載せているのはなぜでしょうか

2023-02-12 16:58 UTC, MikuroXina commented on pages/index.mdx
> +- [shuding/nextra: Simple, powerful and flexible site generation framework with everything you love from Next.js. - GitHub](https://github.com/shuding/nextra)
もし使用フレームワークを紹介するのでしたら, Nextra のリンクだけを貼るのではなく Nextra を用いて作成している旨を書いたほうがよいかと

2023-02-12 16:58 UTC, MikuroXina commented on pages/index.mdx
> +approvers/docs にようこそ
approvers/docs はナビゲーションバーに常に表示されているので, 見出しとしては不自然かと. 「approvers/docs にようこそ」の方を見出しにしたほうが見栄えが良いです

2023-02-12 17:10 UTC, m2en commented on pages/guideline/bot-create-guideline.mdx
> +3. `Privileged Gateway Intents` にある Intent を全てチェックマークボタンから有効化する
それはそう。
これに関しては迷っていて、 Intent は少し仕様が複雑過ぎて Discord API の知識が多少なりともないと何もわからないまま先に進ませてしまう可能性があるので、ここでは全て有効化という強硬手段に出ています

いい表現が思いつかない..... discord.js の ガイド を載せてしまうのも手？

https://discordjs.guide/popular-topics/intents.html

2023-02-12 17:11 UTC, m2en commented on pages/guideline/bot-create-guideline.mdx
> +```ts copy
Nextra の Copy Button 有効化のための指定です。

https://nextra.site/docs/guide/syntax-highlighting#copy-button

2023-02-12 17:13 UTC, m2en commented on pages/index.mdx
> +- [LaTex](https://nextra.site/docs/guide/latex)
後に追加する予定の `CONTRIBUTING.md` に載せる予定のものを一時的にトップページに設置しています。

`CONTRIBUTING.md` 追加時に移動させます。

2023-02-12 17:14 UTC, m2en commented on pages/index.mdx
> +- [shuding/nextra: Simple, powerful and flexible site generation framework with everything you love from Next.js. - GitHub](https://github.com/shuding/nextra)
README にすでにあるので削除します。

2023-02-17 11:02 UTC, MikuroXina requested changes

2023-02-17 11:02 UTC, MikuroXina commented on pages/_meta.json
> +    "title": "Guideline"
```suggestion
    "title": "ガイドライン"
```
日本語にしたほうがよいでしょう

2023-02-17 11:02 UTC, MikuroXina commented on pages/guideline/bot-create-guideline.mdx
> +    // ここにメッセージを受信したときの処理
```suggestion
    # ここにメッセージを受信したときの処理
```
Python のコメントは `#` です

2023-02-17 11:33 UTC, MikuroXina approved these changes

2023-02-17 12:25 UTC, merged