docs: "kebab", not "kabab"
approvers/docs pull request #60
Opened 2023-10-30 21:40 UTC by Nanai10a

2023-10-30 21:51 UTC, Nanai10a commented
to: @m1sk9 
cc: @MikuroXina 

out of scope: "kebab-case" は大文字の英文字を許容していない (常に小文字) (大文字の場合は "SCREAM-KEBAB-CASE"*?*) であり, "lowercase" をわざわざ要求する …或いは単語区切りを "-" で行うことを "kebab" と表現する… のは formal ではないように思えます. 無知なもので, 私のみで断定は出来ないのですが …どう思われますか？

ref: [Naming convention (programming) - Wikipedia #Examples of multiple-word identifier formats](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Examples_of_multiple-word_identifier_formats)
ref: [What is kebab case?](https://www.theserverside.com/definition/Kebab-case)

2023-10-30 22:23 UTC, MikuroXina requested changes
たしかに lowercase は要らないですね. この単語はインラインコードにもすべきではないですし, kebab だけではなく kebab-case と書くべきです

2023-10-31 16:02 UTC, m1sk9 commented
> out of scope: "kebab-case" は大文字の英文字を許容していない (常に小文字) (大文字の場合は "SCREAM-KEBAB-CASE"?) であり, "lowercase" をわざわざ要求する …或いは単語区切りを "-" で行うことを "kebab" と表現する… のは formal ではないように思えます. 無知なもので, 私のみで断定は出来ないのですが …どう思われますか？
@Nanai10a , CC: @MikuroXina 

私も `kebab-case` に表記を改めたほうが良いと思います.

2023-11-01 23:24 UTC, Nanai10a commented
to: @m1sk9, @MikuroXina 

修正しました. Cloudflare Pages の preview にも反映されています. review よろしくお願いします.

2023-11-02 05:35 UTC, MikuroXina approved these changes

2023-11-03 16:08 UTC, merged